apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
data:
  init-mongo.js: |
    db.createUser({
      user: "your-username",
      pwd: "your-password",
      roles: [{ role: "readWrite", db: "your-database" }]
    });

